### ISSUE TITLE
do the functions deal with survey.design objects with a postStrata attribute?

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#3] opened 2015-09-16 02:28 UTC
i believe this is necessary for the pnad?

the `survey::svyCprod` function uses it, but i'm not sure if you carried it over?

https://github.com/DjalmaPessoa/convey/blob/2778c24fa906701dc33e85c94cc1bdb58c0acb26/R/svyarpt.R#L65

i do not believe you need to deal with post-stratification for replicate-weighted designs, but i am not 100% sure?

**Comment by DjalmaPessoa** [comment] 2016-03-10 14:43
To estimate variances we  used the function svyrecvar and had no problem
with the  postStrata atribute.

**Comment by ajdamico** [comment] 2016-03-10 15:37
hi, if have tests that confirm that the all of the `convey` functions are properly dealing with post-stratified survey designs, then i think you can close this issue?  if you are writing up an example, perhaps add a new `analysis examples` script for asdfree for pnad?  you can instruct users to install convey with

    library(devtools)
    install_github('djalmapessoa/convey')

**Comment by DjalmaPessoa** [comment] 2016-03-14 14:28
I've included convey examples using pnad microdata. It might need some cleaning

**Comment by ajdamico** [comment] 2016-03-14 14:31
great!  so you are confident that convey deals with post-stratified designs
correctly?

**Comment by DjalmaPessoa** [comment] 2016-03-14 14:47
the results seem to be reasonable. I don't have results from IBGE to compare with.

**Comment by ajdamico** [comment] 2016-03-14 15:00
will you be able to get them, or are you considering your current computations as final?

**Comment by DjalmaPessoa** [comment] 2016-03-14 17:08
Perhaps I can get point estimates but not the se estimates

**Comment by DjalmaPessoa** [comment] 2016-03-14 18:00
To check the point estimates with results from IBGE see table below figure
5.2 for 2011 in
http://biblioteca.ibge.gov.br/visualizacao/livros/liv91983.pdf .

the estimate by region also matches.

**Comment by ajdamico** [comment] 2016-03-14 18:02
if you are confident that the computations are correct, close this issue :)

**Comment by DjalmaPessoa** [comment] 2016-03-14 18:26
I'm not able to find the script `test_Pnad2011.R` that I included in the
PNAD blog???

**Comment by DjalmaPessoa** [comment] 2016-03-17 14:13
I've included in the file `test_Pnad2011.R` new example of the convey
functions. Bad news: some are not working.   The  svypoormed.survey.design
is working fine. Any idea of what could be wrong?

svypoormed( ~v4720 , y.sub , na.rm = TRUE ) ## not working

I got the result:

*Error in .local(conn, statement, ...) : *
*  Unable to execute statement 'select * from pnad2011 limit 1'.*
*Server says 'integer value too large or not a number (1) in: "select *
from pnad2011 limit 1"*
*' [#22003].*
*In addition: There were 26 warnings (use warnings() to see them) *

**Comment by ajdamico** [comment] 2016-03-17 19:49
this is a monetdblite bug, filed here: https://www.monetdb.org/bugzilla/show_bug.cgi?id=3956

you can work around this issue by setting `options( monetdb.debug.query = TRUE )` at the top of your script

**Comment by ajdamico** [comment] 2016-03-18 11:44
probably should stay open until you can confirm all convey functions work on post-stratified objects..

**Comment by DjalmaPessoa** [comment] 2016-03-28 14:49
When trying to run `svyrmir` for PNAD microdata I noticed that the missing values treatment for `DBIsvydesign` is not working. 

The command inside if(is.na) : 
`design <- design[nas == 0, ]`
should not work since `nas`  is not in the data frame `variables`  of the `design`.

Even worse, this should be true for all functions! This is why I had to complete the `lin` variable with 0 to make them work.

**Comment by DjalmaPessoa** [comment] 2016-04-20 13:57
This the message I get when runing the function svypoormed:
Error in .local(conn, statement, ...) : 
  Unable to execute statement 'select * from pnad2011 limit 1'.
Server says 'integer value too large or not a number (1) in: "select * from pnad2011 limit 1"
' [#22003].

A way out is to set:  options( monetdb.debug.query = TRUE ),  but you mentioned that a more define solution would be implemented

**Comment by ajdamico** [comment] 2016-04-20 14:07
hi, hannes needs to fix, it has been reported in bugzilla..

**Comment by DjalmaPessoa** [comment] 2016-04-20 19:21
In the function svygpg I need to define a formula with a factor with labels 'male' and 'female' (see help), how to do this for the DBIsvydesign class design. Specifically for the pnad2011 examples, we have for the variable v0302 (sex):
 
svytotal(~v0302, design= y.sub, na.rm=TRUE)
                   total     SE
v03022 58321144 166600
v03024 54026378 183998

how to indicate the levels for the sex variable?

**Comment by ajdamico** [comment] 2016-04-21 01:57
maybe this?

y <- update( y , sex = factor( c( 1 , 1 , 2 , 2 )[ v0302 ] , labels = c(
"male" , "female" ) ) )

**Comment by DjalmaPessoa** [comment] 2016-04-21 18:33
I get:

> svytotal(~sex, design= y.sub, na.rm=TRUE)
Error in factor(c(1, 1, 2, 2)[v0302], labels = c("male", "female")) :
  invalid 'labels'; length 2 should be 1 or 0
In addition: Warning message:
'isIdCurrent' is deprecated.
Use 'dbIsValid' instead.
See help("Deprecated")
Note thata in the original microdata: 2 - male; 4 - female

**Comment by ajdamico** [comment] 2016-04-22 10:25
hi, force v0302 to be numeric and it will work--


> y <- update( y , sex = factor( c( 1 , 1 , 2 , 2 )[ as.numeric( v0302 ) ]
, labels = c( "male" , "female" ) ) )
>
>  svytotal( ~ sex , design= y , na.rm = TRUE )
QQ: 'SELECT name, value from sys.env()'
II: Finished in 0s
QQ: 'select v0302 from pnad2011'
II: Finished in 0s
              total     SE
sexmale    95991043 144533
sexfemale 101834240 144533

**Comment by ajdamico** [comment] 2016-06-19 02:33
hi, i am re-opening because there is no way that this issue is finished--  it's a big remaining item on our "to-do" list.  are you certain that `convey` is dealing with post-stratified objects already?  i thought that still required lots of testing.  even if you think the current calculations are correct, we will need to add examples proving it in the ?examples and in the testthat folders..

**Comment by DjalmaPessoa** [comment] 2016-06-19 12:20
After installing the last version of MonetDBLite from the CRAN, I've used
convey with the PNAD2011 microdata and everything worked fine.
I don't have the se from IBGE to match with, but all results seemed
reasonable. So I have reason to believe that convey is working for
post-stratification

**Comment by ajdamico** [comment] 2016-06-19 12:23
great!  but i don't think you should close this issue until you have matched some external post-stratified numbers that you trust?  it is a complicated calculation and it would be safer to find some source to match

**Comment by DjalmaPessoa** [comment] 2016-06-19 12:23
okay

**Comment by DjalmaPessoa** [comment] 2016-06-20 12:52
To compute the linearized variable we consider: the functional form of the indicator and the weights, but to estimate the se we need to take in account the posStratification. The examples show that convey is doing the right thing.

      check if convey works with postStratification
        
        library(survey)
        data(api)
        dclus1<-svydesign(id=~dnum, weights=~pw, data=apiclus1, fpc=~fpc)
        rclus1<-as.svrepdesign(dclus1)
        
        y <- apiclus1$enroll
        
        v1 <- vcov(svytotal(~enroll, dclus1))
        compute the variance like convey
        v2 <- 
          survey::svyrecvar(
            y/dclus1$prob,
            dclus1$cluster,
            dclus1$strata,
            dclus1$fpc,
            postStrata = dclus1$postStrata
          )
        
        v1; v2

      post-stratify on school type
      pop.types <- data.frame(stype=c("E","H","M"), Freq=c(4421,755,1018))
      
      dclus1p<-postStratify(dclus1, ~stype, pop.types)
      rclus1p<-postStratify(rclus1, ~stype, pop.types)
      summary(rclus1p)
      
      v1p <- vcov(svytotal(~enroll, dclus1p))
      
      compute variance using svyrecvar like convey
      
      v2p <-
        survey::svyrecvar(
          y/dclus1p$prob,
          dclus1p$cluster,
          dclus1p$strata,
          dclus1p$fpc,
          postStrata = dclus1p$postStrata
        )
      
      v1p; v2p

**Comment by ajdamico** [comment] 2016-06-20 13:08
@DjalmaPessoa does this belong in a vignette?  users will never see what you have written here..

**Comment by DjalmaPessoa** [comment] 2016-06-20 13:13
I was just trying to convince you that convey  works with
pos-stratification. I hope no use sees it!

**Comment by ajdamico** [comment] 2016-06-20 13:15
haha okay, you can close this issue if you consider it resolved

**Comment by DjalmaPessoa** [comment] 2016-06-20 13:19
I still have to check things for the replication design

**Comment by DjalmaPessoa** [comment] 2017-03-27 14:05
In all convey functions that use linearization, the linearized variable depends on:
1. form of the estimator as function of data
2. design weights.

After computing the linearized variable, we use the design to estimate the variance o a total. For this it was used the function svyrecvar that works with post-stratified design. So,  I don't see which could be the problem.

But we could  try to compare with the vardpoor library results, that has also examples for calibrated designs.

**Comment by DjalmaPessoa** [comment] 2017-04-06 17:29
The **vardpoor** library computes variances for calibration using the function **var_residual** which computes the residuals of a regression and use them to estimate variances.  The same is done by **survey** using the **calibrate** function. In **convey** we use the survey  **calibrated design** object to estimate the variance of the linearized variable, which  is the correct thing to do. 

People at IBGE are using convey (experimental) to estimate  gini from PNAD (post-stratified)  and so far the estimates match to five decimal places with the published results,  and all **se** results from **convey** seem to be reasonable. They have a very good feeling about cv results for the country and regions and are using **replicated design** to check results.
  
So, I think we should close this issue.

**Comment by ajdamico** [comment] 2017-04-06 17:30
thanks djalma

**Closed by DjalmaPessoa** 2017-04-06 17:29 UTC
Labels: enhancement
