### ISSUE TITLE
Replicate this presentation

### ISSUE THREAD

**Issue by guilhermejacob** [DjalmaPessoa/convey#214] opened 2016-12-25 15:09 UTC
In 2014, professors Ramirez and McLeod did [this interesting presentation](http://www.gdsnet.org/PovertyMeasureswithStatavsRSoftware2B.pdf) using Stata to estimate poverty measures.

Back then, there wasn't a R package using the complex survey design to estimate results. But now we can do some of those.
Should we reply to them?

**Comment by ajdamico** [comment] 2016-12-25 17:23
the stata output here isn't close to our `svyfgt` output.  it's a different calculation.  are they making a mistake, or are we?  code below reproduces the numbers on pdf page 6, which are not close to `convey::svyfgt`  thanks



	library(haven)
	x <- read_dta( "http://www.gdsnet.org/sumaria2011.dta" )

	library(survey)

	library(convey)

	y <- svydesign( ~ conglome , strata = ~ estrato , data = x , weights = ~ facpob )
	y <- convey_prep( y )

	linea <- svymean( ~ linea , y )

	# incorrect survey design
	w <- svydesign( ~ 1 , data = x , weights = ~ facpob )

	# matches the p0 row of PDF page 6 of
	# http://www.gdsnet.org/PovertyMeasureswithStatavsRSoftware2B.pdf
	svymean( ~ as.numeric( gpcm < linea ) , w )
								# mean     SE
	# as.numeric(gpcm < linea) 0.27824 0.0042
	
	confint( svymean( ~ as.numeric( gpcm < linea ) , w ) , df = degf( w ) )
								 # 2.5 %    97.5 %
	# as.numeric(gpcm < linea) 0.2701086 0.2863772


	# does not match?
	svyfgt( ~ gpcm , y , abs_thresh = linea , g = 0 )

**Comment by guilhermejacob** [comment] 2016-12-27 01:16
@ajdamico , this is a good point. I found out why they don't match: they don't use a single poverty line. Each stratum seems to have its own poverty line, therefore its very weird for us. So when they use `linea` in their functions, it is not actually a scalar `linea`, but a vector `linea` inside the dataset!

Either way, if the local poverty line is mean-based and used as a reference in the national estimate, the national estimate itself is not based on the national mean, but in a function of means. They seem to have ignored both aspects of this:  the variance of local means and the complicated overall poverty line, which is not absolute nor strictly mean-based. Weird, right?

For instance, if you ignore the fact that the variance is wrong and keep using local-based poverty lines for the overall estimate, this would give us page 6:
```
# matches the p0 row of PDF page 6 of
# http://www.gdsnet.org/PovertyMeasureswithStatavsRSoftware2B.pdf
svymean( ~ as.numeric( gpcm < linea ) , y )
confint( svymean( ~ as.numeric( gpcm < linea ) , y ) , df = degf( y ) )

# poverty gap
svymean( ~ as.numeric( (gpcm < linea)* (linea - gpcm) / linea ) , y )

# squared poverty gap
svymean( ~ as.numeric( (gpcm < linea)* (linea - gpcm)^2 / linea^2 ) , y )
```

When they say that the difference between Stata and R in the last table comes from not using sample weights, they are partially right. We reproduce the wrong results like this.
```
# extreme poverty
svyfgt( ~ gpcm , m , abs_thresh = 143.03 , g = 0, na.rm = T )

# poverty
svyfgt( ~ gpcm , m , abs_thresh = 272.26 , g = 0, na.rm = T )
```

So... bad example :\

**Comment by ajdamico** [comment] 2016-12-27 15:55
closing this because i think we're good with the svyfgt example?  but reopen if i'm missing something?  thanks

**Closed by ajdamico** 2016-12-27 15:55 UTC
Labels: question
