### ISSUE TITLE
additional information in the svyfgt output

### ISSUE THREAD

**Issue by DjalmaPessoa** [DjalmaPessoa/convey#31] opened 2015-11-16 12:28 UTC
Perhaps it would be useful to include the following information:
1. type of threshold: abs, relq, relm
2. value of threshold
3. Instead of fgt could be fgt0 or fgt1 or in general : paste0("fgt", g)

**Comment by ajdamico** [comment] 2015-11-16 12:33
could they just be include the same way that most functions include both
coef and SE objects in the cvystat object?

**Comment by DjalmaPessoa** [comment] 2016-03-10 14:33
To add the additional information, do I have to create a new class and a
new  print for this class?

**Comment by ajdamico** [comment] 2016-03-10 15:48
i believe this is a duplicate of https://github.com/DjalmaPessoa/convey/issues/33 but reopen if you disagree :)

**Closed by ajdamico** 2016-03-10 15:48 UTC
